### ISSUE TITLE
not work for android 12

### ISSUE THREAD

**Issue by junko2013** [SNNafi/variable_app_icon#1]
first of all,thanks for your works!!!

It works fine on iOS platform,but doesn't work for android 12 and emulator,shows exception below:

MissingPluginException(No implementation found for method changeAppIcon on channel variable_app_icon):#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
I/flutter ( 9307): <asynchronous suspension>
I/flutter ( 9307): #1      MethodChannelVariableAppIcon.changeAppIcon (package:variable_app_icon/variable_app_icon_method_channel.dart:15:21)

**Comment by SNNafi** [comment]
Thanks for pointing out the issue.And sorry for late reply.

**Comment by LuisTellez** [comment]
Hi, first of all, thanks for your works

So, I have this error for Android :(

[  +36 ms] package identifier or launch activity not found.
[   +1 ms] Please check /Users/peter/dev/github/activity_alias/android/app/src/main/AndroidManifest.xml for errors.
[   +3 ms] No application found for TargetPlatform.android_x86.
           Is your project missing an android/app/src/main/AndroidManifest.xml?
           Consider running "flutter create ." to create one.

this happen when comment <category android:name="android.intent.category.LAUNCHER"/> from the Activity
Any idea ?

**Comment by SNNafi** [comment]
@LuisTellez, AFAIK flutter doesn't support __mips__ and  __x86__ architectures. Flutter only supports __x86_64__, __armeabi-v7a__, __arm64-v8a__.

**Comment by LuisTellez** [comment]
Same issue with :(

No application found for TargetPlatform.android_arm64.
Is your project missing an android/app/src/main/AndroidManifest.xml?
Consider running "flutter create ." to create one.

Emu: Pixel 3a APi 33 arm64-v8a

**Comment by SNNafi** [comment]
This is a flutter-related issue. However `flutter build apk` is working. But an error occurs while running by `flutter run`. Only happens when `activity-alias` is used as an `android.intent.category.LAUNCHER` instead of an `activity`.

I have given a [PR](https://github.com/flutter/flutter/pull/146548) to fix this.

**Comment by SNNafi** [comment]
@junko2013 , Fixed in latest version `0.0.3`
