### ISSUE TITLE
Does not work on physical iPhone device before device reboot.

### ISSUE THREAD

**Issue by yamashita-room-335** [SNNafi/variable_app_icon#3]
# Environment

iPhone SE 3rd
iOS version: 17.4.1
language: Japanese

<details><summary>flutter doctor -v</summary>

[✓] Flutter (Channel stable, 3.19.6, on macOS 13.6.6 22G630 darwin-x64, locale ja-JP)
    • Flutter version 3.19.6 on channel stable at /Users/suguru/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (2 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/suguru/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • SUGURU の iPhone (mobile) • 00008030-001965641E45802E            • ios            • iOS 17.4.1 21E236
    • iPhone 15 (mobile)       • 1FF9CAFD-9DA2-4E98-9B62-965DD03246D3 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)          • macos                                • darwin-x64     • macOS 13.6.6 22G630 darwin-x64
    • Chrome (web)             • chrome                               • web-javascript • Google Chrome 124.0.6367.119
    ! Error: Browsing on the local area network for sugurのiPad. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
</details>

# Procedure

1. Get the sample app from this repository and set the Signing Team to myself (Personal Team) in Xcode.

1. Install the app on the actual device using the Run button in Android Studio.
(Since this is the Run button, the app is running in Debug Mode.)

1. Select app icon from the drop-down.

-> A dialog will appear, but no changes are made on the iOS Home screen.
The following log is then output.

<details><summary>Xcode log(~ part is my added)</summary>

```
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
flutter: The Dart VM service is listening on http://127.0.0.1:54152/_OMQ_CweHqc=/
flutter: 2

~ select dropdown ~

+[LSApplicationProxy applicationProxyFor*] is not a supported method for getting the LSApplicationProxy for the current process, use +[LSBundleProxy bundleProxyForCurrentProcess] instead.
LaunchServices: store (null) or url (null) was nil: Error Domain=NSOSStatusErrorDomain Code=-54 "process may not map database" UserInfo={NSDebugDescription=process may not map database, _LSLine=67, _LSFunction=_LSServer_GetServerStoreForConnectionWithCompletionHandler}
Attempt to map database failed: permission was denied. This attempt will not be retried.
Failed to initialize client context with error Error Domain=NSOSStatusErrorDomain Code=-54 "process may not map database" UserInfo={NSDebugDescription=process may not map database, _LSLine=67, _LSFunction=_LSServer_GetServerStoreForConnectionWithCompletionHandler}
```
</details>

**But when I reboot the device, the app icon had been changed!**

Restarting the app* and selecting another icon from the drop-down changed it instantly this time.
(*On the actual device, tapping the app icon does not launch the app on iOS home screen, so I tap the Run button on Android Studio.)

Is this behavior common where the icon is not changed before a restart is performed?
And does this behavior not occur in Release Build or Test Flight?

Please let me know if you have any information.

If it is a common behavior, it would be great if you could add it to the pub.dev readme.

**Comment by SNNafi** [comment]
iOS caches the app icon for some weird reason sometimes. Maybe this is the case for you. 

https://stackoverflow.com/questions/58223730/ios-app-showing-old-app-icon-even-after-change
