### ISSUE TITLE
I encountered an error while running ?

### ISSUE THREAD

**Issue by a13020796019** [SNNafi/variable_app_icon#6]
After integrating into my project, it still cannot run.
Then I ran the demo again and got the same error.

Launching lib\main.dart on 21051182C in debug mode...
package identifier or launch activity not found.
Please check E:\Downloads\variable_app_icon-0.0.3\example\android\app\src\main\AndroidManifest.xml for errors.
No application found for TargetPlatform.android_arm64.
Is your project missing an android\app\src\main\AndroidManifest.xml?
Consider running "flutter create ." to create one.

Exited (1).

**Comment by SNNafi** [comment]
Check here https://github.com/SNNafi/variable_app_icon/issues/4
